import SwiftUI

struct ActivityEvent: Identifiable { let id:String; let timestamp:Date; var phase:String; var origin:String; var tool:String; var command:String; var target:String; var output:String; var exitCode:String; var duration:TimeInterval?; var category:String; var raw:String }
final class ActivityStore: ObservableObject {
    @Published private(set) var events:[ActivityEvent]=[]; private let url=FileManager.default.homeDirectoryForCurrentUser.appendingPathComponent(".redtrace/codex-events.jsonl"); private var offset:UInt64=0; private var partial=""; private var starts:[String:ActivityEvent]=[:]; private var timer:Timer?
    init(){timer=Timer.scheduledTimer(withTimeInterval:1.0/12,repeats:true){[weak self]_ in self?.read()}}
    deinit{timer?.invalidate()}; func clear(){try? Data().write(to:url);events=[];offset=0;partial=""}
    private func read(){guard let attrs=try? FileManager.default.attributesOfItem(atPath:url.path),let size=(attrs[.size] as? NSNumber)?.uint64Value else{return};if size<offset{offset=0};guard size>offset,let h=try? FileHandle(forReadingFrom:url)else{return};defer{try?h.close()};try?h.seek(toOffset:offset);let d=(try?h.readToEnd()) ?? Data();offset += UInt64(d.count);let text=partial+String(decoding:d,as:UTF8.self);let parts=text.split(separator:"\n",omittingEmptySubsequences:false);partial=text.hasSuffix("\n") ? "" : String(parts.last ?? "");for line in (text.hasSuffix("\n") ? parts : parts.dropLast()){parse(String(line))}}
    private func parse(_ raw:String){guard let d=raw.data(using:.utf8),let o=(try? JSONSerialization.jsonObject(with:d)) as? [String:Any] else{return};let phase="\(o["phase"] ?? "finish")", tool="\(o["tool_name"] ?? "tool")", command="\(o["command"] ?? "")", input=o["tool_input"].map{"\($0)"} ?? "", target="\(o["target"] ?? o["path"] ?? o["file_path"] ?? o["query"] ?? "")", key="\(o["tool_use_id"] ?? o["session_id"] ?? UUID().uuidString)";let now=ISO8601DateFormatter().date(from:"\(o["timestamp"] ?? "")") ?? Date();var e=ActivityEvent(id:key,timestamp:now,phase:phase,origin:"\(o["origin"] ?? "local")",tool:tool,command:command,target:target,output:"\(o["output"] ?? "")",exitCode:"\(o["exit_code"] ?? "")",duration:nil,category:ActivityStore.category(tool,command),raw:raw+"\n"+input);if phase=="start" {starts[key]=e;return};if let start=starts.removeValue(forKey:key){e.duration=now.timeIntervalSince(start.timestamp);if e.command.isEmpty{e.command=start.command};if e.target.isEmpty{e.target=start.target}};events.append(e);if events.count>3000{events.removeFirst(events.count-3000)} }
    static func category(_ tool:String,_ command:String)->String{let x=(tool+" "+command).lowercased();if x.contains("git "){return "git"};if x.contains("build")||x.contains("xcodebuild"){return "build"};if x.contains("test")||x.contains("pytest"){return "test"};if x.contains("rg ")||x.contains("grep")||x.contains("search"){return "search"};if x.contains("read")||x.contains("get-content")||x.contains("cat "){return "read"};if x.contains("edit")||x.contains("write"){return "edit"};if x.contains("curl")||x.contains("wget"){return "network"};return command.isEmpty ? "tool" : "command"}
    func description(_ e:ActivityEvent)->String{if e.category=="search",!e.target.isEmpty{return "Searching \(e.target)"};if !e.target.isEmpty{return e.target};if !e.command.isEmpty{return e.command};return "\(e.tool) activity"}
}
struct ActivityView: View { @ObservedObject var store:ActivityStore; @AppStorage("chatGPTActivityMode") private var mode="Normal"; var body:some View{VStack(spacing:0){Picker("",selection:$mode){Text("Minimal").tag("Minimal");Text("Normal").tag("Normal");Text("Verbose").tag("Verbose")}.pickerStyle(.segmented).padding(8);ScrollView{LazyVStack(alignment:.leading,spacing:8){ForEach(store.events){e in if mode=="Verbose"{Text("\(e.timestamp) \(e.phase.uppercased()) \(e.origin.uppercased())\nTOOL \(e.tool)\nCMD \(e.command)\nTARGET \(e.target)\n\(e.output)\n\(e.raw)").font(.system(size:11,design:.monospaced)).frame(maxWidth:.infinity,alignment:.leading)}else{HStack(alignment:.top){Image(systemName:e.category=="edit" ? "pencil" : e.category=="build" ? "hammer" : "magnifyingglass").foregroundStyle(e.category=="edit" ? .pink : .orange);VStack(alignment:.leading){Text("\(e.category.uppercased())  \(store.description(e))").font(.system(size:12,weight:.semibold));if mode=="Normal"{Text(e.command).font(.system(size:10,design:.monospaced)).foregroundStyle(.secondary);Text("\(e.origin.uppercased())\(e.duration.map{String(format:" · %.1fs",$0)} ?? "")").font(.caption2).foregroundStyle(.secondary)}}.frame(maxWidth:.infinity,alignment:.leading)}}}.padding(10)}}}
