import Foundation

protocol ComputerBackend: AnyObject { var status: ComputerBackendStatus { get }; var capabilities: ComputerBackendCapabilities { get }; func connect() async throws; func disconnect(); func stopControl(); func permissions() async throws -> ComputerPermissionStatus; func perform(_ action: ComputerAction) async throws }
enum ComputerBackendStatus: Equatable { case disconnected, connecting, connected, unavailable(String) }
struct ComputerPermissionStatus { var accessibility = false; var screenRecording = false }
struct ComputerBackendCapabilities: OptionSet { let rawValue: UInt; static let none = Self([]); static let screenRead = Self(rawValue: 1 << 0); static let pointerInput = Self(rawValue: 1 << 1); static let keyboardInput = Self(rawValue: 1 << 2); static let scrolling = Self(rawValue: 1 << 3) }
enum ComputerAction {
    case capture, inspect, click(x: Double, y: Double), type(String), scroll(dx: Double, dy: Double)
    var tool: String { switch self { case .capture: return "computer_screenshot"; case .inspect: return "computer_read_screen"; case .click: return "computer_click"; case .type: return "computer_type"; case .scroll: return "computer_scroll" } }
    var arguments: [String: Any] { switch self { case .capture, .inspect: return [:]; case let .click(x,y): return ["x":x,"y":y]; case let .type(text): return ["text":text]; case let .scroll(dx,dy): return ["dx":dx,"dy":dy] } }
    var description: String { switch self { case .capture:return "Capture screen";case .inspect:return "Inspect screen";case let .click(x,y):return "Click (\(Int(x)), \(Int(y)))";case let .type(text):return "Type \(text)";case let .scroll(dx,dy):return "Scroll (\(Int(dx)), \(Int(dy)))" } }
}
enum ComputerBackendError: LocalizedError { case missingServer(String), disconnected, server(String); var errorDescription:String? { switch self { case let .missingServer(path):return "Computer-use server is missing: \(path)";case .disconnected:return "Computer-use server is disconnected";case let .server(message):return message } } }

/// Replaceable stdio adapter for virajshoor/opencode-computer-use. Set REDTRACE_COMPUTER_USE_SERVER to dist/index.js.
class ExternalMCPComputerBackend: ComputerBackend {
    private let serverURL: URL?; private let nodeURL: URL?; private let commandArguments: [String]; private let toolMap: [String: String]; private weak var activityStore: ActivityStore?; private let queue = DispatchQueue(label:"RedTrace.ComputerBackend")
    private var process: Process?; private var input: FileHandle?; private var buffer = Data(); private var nextID = 1; private var replies:[Int:(Result<[String:Any],Error>)->Void]=[:]
    private(set) var status: ComputerBackendStatus = .disconnected; private(set) var capabilities: ComputerBackendCapabilities = .none
    init(activityStore: ActivityStore, serverURL: URL? = nil) { self.activityStore=activityStore; self.serverURL=serverURL ?? URL(fileURLWithPath:ProcessInfo.processInfo.environment["REDTRACE_COMPUTER_USE_SERVER"] ?? FileManager.default.homeDirectoryForCurrentUser.appendingPathComponent(".redtrace/opencode-computer-use/dist/index.js").path); self.nodeURL=Self.findNode(); self.commandArguments=[self.serverURL!.path]; self.toolMap=[:] }
    init(activityStore: ActivityStore, commandURL: URL?, arguments: [String], toolMap: [String: String] = [:]) { self.activityStore=activityStore; self.serverURL=nil; self.nodeURL=commandURL; self.commandArguments=arguments; self.toolMap=toolMap }
    func connect() async throws { try await withCheckedThrowingContinuation { continuation in queue.async { self.connect { continuation.resume(with:$0) } } } }
    func disconnect() { queue.async { self.stop(status:.disconnected) } }
    func stopControl() { disconnect() }
    func permissions() async throws -> ComputerPermissionStatus { let result:Result<[String:Any],Error> = await withCheckedContinuation { continuation in queue.async { guard case .connected = self.status else { continuation.resume(returning:.failure(ComputerBackendError.disconnected)); return }; self.request("tools/call",["name":"computer_permissions","arguments":["prompt":false]]) { continuation.resume(returning:$0) } } }; return try Self.permissionStatus(from: result.get()) }
    func perform(_ action: ComputerAction) async throws { let result:Result<[String:Any],Error> = await withCheckedContinuation { continuation in queue.async { guard case .connected = self.status else { continuation.resume(returning:.failure(ComputerBackendError.disconnected));return }; self.activityStore?.recordComputerAction(action,phase:"start");self.request("tools/call",["name":self.toolMap[action.tool] ?? action.tool,"arguments":action.arguments]) { result in self.activityStore?.recordComputerAction(action,phase:"finish",result:try? result.get());continuation.resume(returning:result) } } };_ = try result.get() }
    private func connect(completion:@escaping(Result<Void,Error>)->Void) {
        guard process==nil else {completion(.success(()));return};if let serverURL, !FileManager.default.fileExists(atPath:serverURL.path) {let error=ComputerBackendError.missingServer(serverURL.path);status = .unavailable(error.localizedDescription);completion(.failure(error));return};guard let nodeURL else {let error=ComputerBackendError.server("Computer-use server is not installed.");status = .unavailable(error.localizedDescription);completion(.failure(error));return};status = .connecting
        let process=Process(),stdin=Pipe(),stdout=Pipe();process.executableURL=nodeURL;process.arguments=commandArguments;process.standardInput=stdin;process.standardOutput=stdout
        stdout.fileHandleForReading.readabilityHandler = {[weak self] handle in self?.queue.async {self?.receive(handle.availableData)}};process.terminationHandler = {[weak self] terminated in self?.queue.async {self?.crashed(terminated.terminationStatus)}}
        do {try process.run()}catch {status = .unavailable(error.localizedDescription);completion(.failure(error));return};self.process=process;input=stdin.fileHandleForWriting
        request("initialize",["protocolVersion":"2024-11-05","capabilities":[:],"clientInfo":["name":"RedTrace","version":"1.0"]]) { result in switch result {case .failure(let error):self.stop(status:.unavailable(error.localizedDescription));completion(.failure(error));case .success:self.notify("notifications/initialized");self.request("tools/list",[:]) { tools in switch tools {case .failure(let error):self.stop(status:.unavailable(error.localizedDescription));completion(.failure(error));case .success(let value):self.capabilities=Self.capabilities(from:value);self.status = .connected;completion(.success(()))} } } }
    }
    private func request(_ method:String,_ params:[String:Any],completion:@escaping(Result<[String:Any],Error>)->Void) {let id=nextID;nextID+=1;replies[id]=completion;send(["jsonrpc":"2.0","id":id,"method":method,"params":params])}
    private func notify(_ method:String){send(["jsonrpc":"2.0","method":method,"params":[:] as [String:Any]])}
    private func send(_ value:[String:Any]){guard let input,let data=try? JSONSerialization.data(withJSONObject:value)else{return};input.write(data);input.write(Data([10]))}
    private func receive(_ data:Data){guard !data.isEmpty else{return};buffer.append(data);while let newline=buffer.firstIndex(of:10){let line=buffer.prefix(upTo:newline);buffer.removeSubrange(...newline);guard let value=try? JSONSerialization.jsonObject(with:line) as? [String:Any],let id=value["id"] as? Int,let reply=replies.removeValue(forKey:id)else{continue};if let error=value["error"] as? [String:Any]{reply(.failure(ComputerBackendError.server(error["message"] as? String ?? "MCP request failed")))}else{reply(.success(value["result"] as? [String:Any] ?? [:]))}}}
    private func crashed(_ code:Int32){guard process != nil else{return};stop(status:.unavailable("Computer-use server exited (\(code))"))}
    private func stop(status:ComputerBackendStatus){process?.terminationHandler=nil;process?.terminate();process=nil;input?.closeFile();input=nil;capabilities = .none;self.status=status;let pending=replies;replies.removeAll();pending.values.forEach{$0(.failure(ComputerBackendError.disconnected))}}
    private static func capabilities(from result:[String:Any])->ComputerBackendCapabilities {let names=((result["tools"] as? [[String:Any]]) ?? []).compactMap{$0["name"] as? String}.joined(separator:" ").lowercased();var value:ComputerBackendCapabilities = .none;if names.contains("screenshot") || names.contains("read_screen") || names.contains("get_app_state"){value.insert(.screenRead)};if names.contains("click"){value.insert(.pointerInput)};if names.contains("type") || names.contains("key"){value.insert(.keyboardInput)};if names.contains("scroll"){value.insert(.scrolling)};return value}
    private static func permissionStatus(from result:[String:Any])->ComputerPermissionStatus { var status=ComputerPermissionStatus(); if let content=result["content"] as? [[String:Any]],let text=content.compactMap({$0["text"] as? String}).first,let data=text.data(using:.utf8),let object=try? JSONSerialization.jsonObject(with:data) as? [String:Any] { status.accessibility=object["accessibility"] as? Bool ?? false; status.screenRecording=object["screenRecording"] as? Bool ?? false }; return status }
    fileprivate static func findNode() -> URL? { let fm=FileManager.default;if let override=ProcessInfo.processInfo.environment["REDTRACE_NODE"],fm.isExecutableFile(atPath:override){return URL(fileURLWithPath:override)};for path in ["/usr/local/bin/node","/opt/homebrew/bin/node"] where fm.isExecutableFile(atPath:path){return URL(fileURLWithPath:path)};let versions=fm.homeDirectoryForCurrentUser.appendingPathComponent(".nvm/versions/node");return (try? fm.contentsOfDirectory(at:versions,includingPropertiesForKeys:nil))?.sorted{$0.lastPathComponent>$1.lastPathComponent}.map{$0.appendingPathComponent("bin/node")}.first{fm.isExecutableFile(atPath:$0.path)} }
}

final class OpenComputerUseBackend: ExternalMCPComputerBackend {
    init(activityStore: ActivityStore) { let script=Self.findScript(); super.init(activityStore:activityStore, commandURL:Self.findNode(), arguments:script.map{[$0.path,"mcp"]} ?? [], toolMap:["computer_screenshot":"get_app_state", "computer_read_screen":"get_app_state", "computer_click":"click", "computer_scroll":"scroll", "computer_type":"type_text", "computer_key":"press_key"]) }
    private static func findScript() -> URL? { let fm=FileManager.default; let paths=["/usr/local/bin/open-computer-use","/opt/homebrew/bin/open-computer-use","/usr/local/bin/ocu","/opt/homebrew/bin/ocu"]; if let path=paths.first(where:{fm.isExecutableFile(atPath:$0)}) { return URL(fileURLWithPath:path) }; let versions=fm.homeDirectoryForCurrentUser.appendingPathComponent(".nvm/versions/node"); return (try? fm.contentsOfDirectory(at:versions,includingPropertiesForKeys:nil))?.sorted{$0.lastPathComponent>$1.lastPathComponent}.map{$0.appendingPathComponent("bin/open-computer-use")}.first{fm.isExecutableFile(atPath:$0.path)} }
}
