import AppKit

struct TerminalColor: Equatable { var rgb: NSColor?; static let `default` = TerminalColor(rgb: nil) }
struct TerminalStyle: Equatable { var foreground = TerminalColor.default; var background = TerminalColor.default; var bold = false; var dim = false; var italic = false; var underline = false; var inverse = false }
struct TerminalCell: Equatable { var character: Character = " "; var style = TerminalStyle() }

/// A bounded VT screen. Parsing is byte based so UTF-8 and CSI sequences can span reads.
final class TerminalModel {
    private(set) var columns: Int; private(set) var rows: Int
    private var primary: [[TerminalCell]]; private var alternate: [[TerminalCell]]
    private var useAlternate = false; private var cursor = (0, 0); private var saved = (0, 0)
    private var style = TerminalStyle(); private var carry = [UInt8](); private var utf8 = [UInt8]()
    private var scrollTop = 0; private var scrollBottom: Int; private(set) var cursorVisible = true
    private(set) var bracketedPaste = false; private var scrollback = [[TerminalCell]]()
    var onResponse: ((Data) -> Void)?; var onDirty: (() -> Void)?
    init(columns: Int = 100, rows: Int = 30) { self.columns = max(2, columns); self.rows = max(1, rows); primary = Array(repeating: Array(repeating: TerminalCell(), count: max(2, columns)), count: max(1, rows)); alternate = primary; scrollBottom = max(1, rows) - 1 }
    private var screen: [[TerminalCell]] { get { useAlternate ? alternate : primary } set { if useAlternate { alternate = newValue } else { primary = newValue } } }
    func resize(columns: Int, rows: Int) { let c = max(2, columns), r = max(1, rows); guard c != self.columns || r != self.rows else { return }; self.columns = c; self.rows = r; primary = resize(primary, c, r); alternate = resize(alternate, c, r); cursor.0 = min(cursor.0, r - 1); cursor.1 = min(cursor.1, c - 1); scrollBottom = r - 1; dirty() }
    private func resize(_ old: [[TerminalCell]], _ c: Int, _ r: Int) -> [[TerminalCell]] { Array(old.prefix(r)).map { Array($0.prefix(c)) + Array(repeating: TerminalCell(), count: max(0, c-$0.count)) } + Array(repeating: Array(repeating: TerminalCell(), count: c), count: max(0, r-old.count)) }
    func clear() { primary = Array(repeating: Array(repeating: TerminalCell(), count: columns), count: rows); alternate = primary; cursor = (0,0); saved = (0,0); scrollback.removeAll(); dirty() }
    func lines() -> [[TerminalCell]] { screen }
    func feed(_ data: Data) { var bytes = carry + Array(data); carry.removeAll(); var i = 0; while i < bytes.count { let b = bytes[i]; if b == 0x1b { guard i+1 < bytes.count else { carry = [b]; break }; let n = bytes[i+1]; if n == 0x5b { var e=i+2; while e < bytes.count && !(0x40...0x7e).contains(bytes[e]) { e += 1 }; guard e < bytes.count else { carry = Array(bytes[i...]); break }; csi(String(bytes: bytes[(i+2)..<e], encoding:.ascii) ?? "", final: bytes[e]); i=e+1; continue }; if n == 0x5d { var e=i+2; while e < bytes.count && bytes[e] != 7 && !(bytes[e] == 27 && e+1 < bytes.count && bytes[e+1] == 92) { e += 1 }; guard e < bytes.count else { carry = Array(bytes[i...]); break }; i += bytes[e] == 7 ? e-i+1 : e-i+2; continue }; esc(n); i += 2; continue }
        switch b { case 8: cursor.1=max(0,cursor.1-1); case 9: cursor.1=min(columns-1,((cursor.1/8)+1)*8); case 10: lineFeed(); case 13: cursor.1=0; case 0...31,127: break; default: utf8.append(b); decodeUTF8() }; i += 1 }; dirty() }
    private func decodeUTF8() { guard let s=String(bytes:utf8,encoding:.utf8) else { if utf8.count > 4 { put("�"); utf8.removeAll() }; return }; for ch in s { put(ch) }; utf8.removeAll() }
    private func put(_ ch: Character) { var s=screen; s[cursor.0][cursor.1]=TerminalCell(character:ch,style:style); screen=s; cursor.1 += 1; if cursor.1 >= columns { cursor.1=0; lineFeed() } }
    private func lineFeed() { if cursor.0 == scrollBottom { if !useAlternate { scrollback.append(screen[scrollTop]); if scrollback.count > 5000 { scrollback.removeFirst(scrollback.count-5000) } }; var s=screen; s.remove(at:scrollTop); s.insert(Array(repeating:TerminalCell(),count:columns),at:scrollBottom); screen=s } else { cursor.0=min(rows-1,cursor.0+1) } }
    private func esc(_ b: UInt8) { switch b { case 55: saved=cursor; case 56: cursor=saved; case 68: lineFeed(); case 77: cursor.0=max(scrollTop,cursor.0-1); case 69: lineFeed(); cursor.1=0; case 99: clear(); default: break } }
    private func csi(_ raw: String, final: UInt8) { let privateMode=raw.hasPrefix("?"); let p=raw.trimmingCharacters(in:CharacterSet(charactersIn:"?<>=")); let v=p.split(separator:";",omittingEmptySubsequences:false).map{Int($0) ?? 0}; func n(_ x:Int,_ d:Int=1)->Int { x<v.count && v[x] != 0 ? v[x] : d }
        if privateMode { let mode=v.first ?? 0; if final == 104 /*h*/ { if mode==25 {cursorVisible=true}; if [47,1047,1049].contains(mode) {useAlternate=true; alternate=Array(repeating:Array(repeating:TerminalCell(),count:columns),count:rows); cursor=(0,0)}; if mode==2004 {bracketedPaste=true} }; if final == 108 /*l*/ { if mode==25 {cursorVisible=false}; if [47,1047,1049].contains(mode) {useAlternate=false}; if mode==2004 {bracketedPaste=false} }; return }
        switch final { case 65: cursor.0=max(scrollTop,cursor.0-n(0)); case 66: cursor.0=min(scrollBottom,cursor.0+n(0)); case 67: cursor.1=min(columns-1,cursor.1+n(0)); case 68: cursor.1=max(0,cursor.1-n(0)); case 69: cursor.0=min(scrollBottom,cursor.0+n(0));cursor.1=0; case 70: cursor.0=max(scrollTop,cursor.0-n(0));cursor.1=0; case 71: cursor.1=min(columns-1,n(0)-1); case 72,102: cursor.0=min(rows-1,n(0)-1);cursor.1=min(columns-1,n(1)-1); case 74: eraseDisplay(v.first ?? 0); case 75: eraseLine(v.first ?? 0); case 80: delete(n(0)); case 88: erase(n(0)); case 64: insert(n(0)); case 76: insertLines(n(0)); case 77: deleteLines(n(0)); case 83: scroll(n(0)); case 84: reverseScroll(n(0)); case 114: scrollTop=max(0,n(0)-1);scrollBottom=min(rows-1,n(1,rows)-1);cursor=(scrollTop,0); case 115: saved=cursor; case 117: cursor=saved; case 109: sgr(v); case 110: if v.first==5 {onResponse?(Data("\u{1b}[0n".utf8))} else if v.first==6 {onResponse?(Data("\u{1b}[\(cursor.0+1);\(cursor.1+1)R".utf8))}; default: break } }
    private func eraseLine(_ mode:Int) { var s=screen; let r=cursor.0; let range = mode==1 ? 0...cursor.1 : mode==2 ? 0...(columns-1) : cursor.1...(columns-1); for i in range {s[r][i]=TerminalCell()};screen=s }
    private func eraseDisplay(_ mode:Int) { if mode==2 || mode==3 { if mode==3 {scrollback.removeAll()}; screen=Array(repeating:Array(repeating:TerminalCell(),count:columns),count:rows);cursor=(0,0);return }; eraseLine(mode==1 ? 1:0) }
    private func delete(_ count:Int) { var s=screen; let r=cursor.0; s[r].removeSubrange(cursor.1..<min(columns,cursor.1+count)); s[r]+=Array(repeating:TerminalCell(),count:columns-s[r].count);screen=s }; private func erase(_ count:Int){var s=screen;for i in cursor.1..<min(columns,cursor.1+count){s[cursor.0][i]=TerminalCell()};screen=s}; private func insert(_ count:Int){var s=screen;s[cursor.0].insert(contentsOf:Array(repeating:TerminalCell(),count:count),at:cursor.1);s[cursor.0]=Array(s[cursor.0].prefix(columns));screen=s}
    private func insertLines(_ n:Int){var s=screen;for _ in 0..<n{s.insert(Array(repeating:TerminalCell(),count:columns),at:cursor.0);s.remove(at:scrollBottom)};screen=s}; private func deleteLines(_ n:Int){var s=screen;for _ in 0..<n{s.remove(at:cursor.0);s.insert(Array(repeating:TerminalCell(),count:columns),at:scrollBottom)};screen=s};private func scroll(_ n:Int){for _ in 0..<n {var s=screen;s.remove(at:scrollTop);s.insert(Array(repeating:TerminalCell(),count:columns),at:scrollBottom);screen=s}};private func reverseScroll(_ n:Int){for _ in 0..<n {var s=screen;s.remove(at:scrollBottom);s.insert(Array(repeating:TerminalCell(),count:columns),at:scrollTop);screen=s}}
    private func sgr(_ values:[Int]) { var a=values.isEmpty ? [0] : values; var i=0; while i<a.count { let x=a[i]; switch x { case 0:style=TerminalStyle();case 1:style.bold=true;case 2:style.dim=true;case 3:style.italic=true;case 4:style.underline=true;case 7:style.inverse=true;case 22:style.bold=false;style.dim=false;case 23:style.italic=false;case 24:style.underline=false;case 27:style.inverse=false;case 30...37,90...97:style.foreground=color(x);case 40...47,100...107:style.background=color(x);case 39:style.foreground=.default;case 49:style.background=.default;case 38,48: if i+2<a.count && a[i+1]==5 {let c=TerminalColor(rgb:ansi256(a[i+2]));if x==38{style.foreground=c}else{style.background=c};i+=2} else if i+4<a.count && a[i+1]==2 {let c=TerminalColor(rgb:NSColor(calibratedRed:CGFloat(a[i+2])/255,green:CGFloat(a[i+3])/255,blue:CGFloat(a[i+4])/255,alpha:1));if x==38{style.foreground=c}else{style.background=c};i+=4};default:break };i+=1 } }
    private func color(_ x:Int)->TerminalColor { let n = x>=90 ? x-90+8 : x>=40 ? x-40 : x-30; return TerminalColor(rgb:ansi256(n)) }; private func ansi256(_ n:Int)->NSColor { let base:[NSColor]=[.black,.systemRed,.systemGreen,.systemYellow,.systemBlue,.systemMagenta,.systemCyan,.lightGray,.darkGray,.systemRed,.systemGreen,.systemYellow,.systemBlue,.systemMagenta,.systemCyan,.white]; if n<16{return base[n]};if n>=232 {let g=CGFloat(8+(n-232)*10)/255;return NSColor(calibratedWhite:g,alpha:1)};let q=n-16;return NSColor(calibratedRed:CGFloat(q/36)/5,green:CGFloat((q/6)%6)/5,blue:CGFloat(q%6)/5,alpha:1) }
    private func dirty(){onDirty?()}
}
